apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.18.4"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system

  valuesFrom:
    # 1. Dynamic IP (From Justfile)
    # Correct: No 'valuesKey' because Justfile uses --from-literal (Raw Keys)
    - kind: ConfigMap
      name: cilium-env-values
      optional: false

    # 2. Static Config (From Kustomize)
    # Corrected: Must match the key defined in kustomization.yaml
    - kind: ConfigMap
      name: cilium-static-values
      valuesKey: values.yaml
      optional: false
