apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.fullname" . }}-secret
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
type: Opaque
data:
  # Use keys from values.yaml or generate random ones
  RUSTFS_ACCESS_KEY: {{ .Values.auth.accessKey | default (randAlphaNum 20) | b64enc | quote }}
  RUSTFS_SECRET_KEY: {{ .Values.auth.secretKey | default (randAlphaNum 40) | b64enc | quote }}