# clusters/dev/platform.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  # Points to the platform services
  path: ./platform/dev
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure
