apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: open-data-platform
  # POINT TO THE DEV OVERLAY
  path: ./platform/dev
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure
