#!/bin/bash

# CONFIGURATION
export GATEWAY_API_VERSION="v1.2.0"
export CILIUM_VERSION="1.18.4"
export CERT_MANAGER="1.16.2"

echo "🚀 Starting Local Cluster Setup (sslip.io + kind-gateway)..."

# 1. ADD HELM REPOS
# ====================================================================
echo "📦 Adding Helm repositories..."
helm repo add cilium https://helm.cilium.io/
helm repo add jetstack https://charts.jetstack.io
helm repo update

# 2. GATEWAY API CRD SETUP
# ====================================================================
echo "🔗 Installing Gateway API CRDs..."
kubectl apply -k "https://github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=${GATEWAY_API_VERSION}"

# 3. INSTALL CILIUM
# ====================================================================
echo "🐝 Installing Cilium..."
helm upgrade --install cilium cilium/cilium --version ${CILIUM_VERSION} \
    --namespace kube-system \
    --create-namespace \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=true \
    --set operator.replicas=1 \
    --set gatewayAPI.enabled=true \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set l2announcements.enabled=true \
    --set externalIPs.enabled=true

echo "⏳ Waiting for Cilium to be ready..."
kubectl -n kube-system rollout status deployment/cilium-operator
kubectl -n kube-system rollout status ds/cilium --timeout=5m

# 4. INSTALL CERT MANAGER
# ====================================================================
echo "🔒 Installing Cert-Manager..."
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v${CERT_MANAGER}/cert-manager.crds.yaml

helm upgrade --install cert-manager jetstack/cert-manager --version v${CERT_MANAGER} \
    --namespace cert-manager \
    --create-namespace \
    --wait \
    --set config.apiVersion="controller.config.cert-manager.io/v1alpha1" \
    --set config.kind="ControllerConfiguration" \
    --set config.enableGatewayAPI=true

# 5. SETUP CA & GATEWAY
# ====================================================================
echo "📝 Creating CA Infrastructure..."
# Apply the CA Issuer first so the Certificate in the next step can find it
kubectl apply -f ./components/network/cilium/ca-issuer.yaml
sleep 2

echo "🚪 Applying Gateway Configuration..."
# Applies: Class, Certificate (kind-gateway-tls), and Gateway (kind-gateway)
kubectl apply -f ./components/network/cilium/gateway/

# 6. THE CRITICAL PATCH
# ====================================================================
echo "🔧 Patching 'cilium-gateway-kind-gateway' to bind to Host Ports..."

# Wait for the specific Service name generated by Cilium
while ! kubectl get svc cilium-gateway-kind-gateway -n default &> /dev/null; do
    echo "   ... waiting for Service 'cilium-gateway-kind-gateway' to appear"
    sleep 2
done

# Force NodePort 30080 (HTTP) and 30443 (HTTPS)
# This connects the Kind 'extraPortMappings' to the Cilium Gateway
kubectl patch svc cilium-gateway-kind-gateway -n default --type='json' -p='[
  {"op": "replace", "path": "/spec/type", "value": "NodePort"},
  {"op": "replace", "path": "/spec/ports/0/nodePort", "value": 30080},
  {"op": "replace", "path": "/spec/ports/1/nodePort", "value": 30443}
]'

echo "=================================================================="
echo "🎉 CLUSTER SETUP COMPLETE!"
echo "🚀 HTTPS enabled: https://<service>.127.0.0.1.sslip.io"
echo "ℹ️  Don't forget to import the CA from 'components/network/cilium/ca-issuer.yaml'"
echo "   into your browser/OS trust store to remove the warning!"
echo "=================================================================="