# This file defines your entire application stack.
# Run 'helmfile sync' to apply everything.
# Run 'helmfile destroy' to remove everything.

################################################################################
# REPOSITORIES
#
# This block lists the Helm chart repositories we need.
################################################################################
repositories:
  # K8s Dashboard for cluster management
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: lakekeeper
    url: https://lakekeeper.github.io/lakekeeper-charts/
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: cilium
    url: https://helm.cilium.io/

# NOTE: OCI charts (like Rustfs) do not go in this 'repositories' block.
# They are referenced directly in the 'releases' block.

################################################################################
# RELEASES
#
# This block lists all the applications (charts) to install.
################################################################################
releases:
  # NGINX Ingress Controller
  - name: nginx-ingress
    chart: oci://ghcr.io/nginxinc/charts/nginx-ingress
    version: 1.0.0
    # It's best practice to put the ingress controller in its own namespace
    namespace: nginx-ingress
    createNamespace: true

  # Rustfs Object Storage
  - name: rustfs
    # The 'chart:' line for OCI charts is the full URL.
    chart: oci://registry-1.docker.io/cloudpirates/rustfs
    version: 0.1.0
    namespace: default
    createNamespace: true
    values:
      - ./components/object-storage/rustfs/values.yml

  # CNPG Operator (The "Brain")
  - name: cnpg-operator
    chart: cnpg/cloudnative-pg
    version: 0.26.1
    namespace: database
    createNamespace: true
    values:
      - ./components/database/cloud-native-pg/operator.values.yml

  # CNPG Cluster (The Postgres Cluster itself)
  - name: cnpg-cluster
    chart: cnpg/cluster
    version: 0.26.1
    namespace: database
    createNamespace: false
    values:
      - ./components/database/cloud-native-pg/cluster.values.yml
    needs:
      - database/cnpg-operator

  # Lakekeeper Data Lake
  - name: lakekeeper
    chart: lakekeeper/lakekeeper
    version: 0.8.1
    namespace: default
    createNamespace: false
    values:
      - ./components/governance/lakekeeper/values.yml
    needs:
      - database/cnpg-cluster

  # # Hubble - The Cilium Observability UI
  # - name: hubble
  #   chart: cilium/hubble
  #   version: 1.18.3
  #   namespace: kube-system # Installs alongside Cilium
  #   values:
  #     - ui:
  #         enabled: true
