# 1. The Bootstrap Issuer (Self-Signed)
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed
  namespace: cert-manager
spec:
  selfSigned: {}
---
# 2. The Root CA Certificate (Generates the Secret)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Local Dev Root CA" # Helpful name for debugging
  secretName: ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: self-signed
    kind: Issuer
    group: cert-manager.io # Explicitly state group
---
# 3. The ClusterIssuer (Consumes the Secret)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-cluster-issuer
spec:
  ca:
    secretName: ca
