apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.18.4"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system

  valuesFrom:
    # 1. Dynamic IP (Created by Justfile)
    # NO 'valuesKey' here! We want the raw keys (k8sServiceHost) merged directly.
    - kind: ConfigMap
      name: cilium-env-values
      optional: false

    # 2. Static Config (Created by Kustomize)
    # YES 'valuesKey' here! We want to parse the 'values.yaml' string inside.
    - kind: ConfigMap
      name: cilium-static-values
      valuesKey: values.yaml
      optional: false
