apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.18.4"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system

  valuesFrom:
    # 1. Dynamic IP (From Justfile)
    # CRITICAL: Do NOT put 'valuesKey' here.
    # We want the raw keys (k8sServiceHost) to be merged as-is.
    - kind: ConfigMap
      name: cilium-env-values
      optional: false

    # 2. Static Config (From Kustomize Generator)
    # CRITICAL: MUST have 'valuesKey'.
    # We want to unpack the YAML string inside this key.
    - kind: ConfigMap
      name: cilium-static-values
      valuesKey: values.yaml
      optional: false
