apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kind-wildcard-cert
  namespace: default
spec:
  secretName: kind-gateway-tls

  issuerRef:
    name: ca-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io

  # Using specific hostname and sslip.io
  commonName: "prefect.127.0.0.1.sslip.io"
  dnsNames:
    - "prefect.127.0.0.1.sslip.io"
