apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  install:
    createNamespace: true
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    config:
      apiVersion: "controller.config.cert-manager.io/v1alpha1"
      kind: "ControllerConfiguration"
      enableGatewayAPI: true
