apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  install:
    createNamespace: true
  interval: 1h

  # --- ADD THIS DEPENDENCY ---
  # This ensures CNI (Cilium) is Ready before Cert-Manager tries to start.
  dependsOn:
    - name: cilium
      namespace: kube-system
  # ---------------------------

  chart:
    spec:
      chart: cert-manager
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    config:
      apiVersion: "controller.config.cert-manager.io/v1alpha1"
      kind: "ControllerConfiguration"
      enableGatewayAPI: true
