apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prefect
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: prefect-worker
      version: "2025.11.21180339"
      sourceRef:
        kind: HelmRepository
        name: prefect
        namespace: flux-system
  dependsOn:
    - name: infrastructure
      namespace: flux-system
