apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prefect
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: prefect-server
      version: "25.11.24182903"
      sourceRef:
        kind: HelmRepository
        name: prefect
        namespace: flux-system
