apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prefect-external-access
  namespace: prefect # Route lives where the App lives
spec:
  parentRefs:
    - name: internet-gateway # Name of your Gateway
      namespace: default # Gateway lives in 'default'
      sectionName: https # Attach to the HTTPS listener (Port 443)
  hostnames:
    - "prefect.localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prefect-server # Confirmed service name
          port: 4200 # Confirmed service port
